language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rosuna/demo-dockerization -f Dockerfile.dev .

script:
  - docker run -e CI=true rosuna/demo-dockerization npm run test